package com.project.GUI;

import com.project.dto.Client;
import com.project.dto.Jou;
import com.project.repository.JourneyDB;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Miguel
 */
public class ClientJourney extends javax.swing.JFrame {

	private String mode = "all";
	private String filter = null;
	private String searchword;
	private void jTextField1ActionPerformed() {
		// TODO Auto-generated method stub
		searchword = jTextField1.getText();
		Object [][] tableBody = Controller.Requests.tableJourneySetter(mode,"client", filter, searchword);
        String [] tableTitles = new String [] {
        		"ID", "Port of Origin", "Destination", "Content", "Company", "Container ID", "Status"
            };
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(tableBody,tableTitles));
	}
	
    /**
     * Creates new form ClientJourney
     */
    public ClientJourney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMenuItem jMenuItem1 = new JMenuItem();
        JCheckBoxMenuItem jCheckBoxMenuItem1 = new JCheckBoxMenuItem();
        JMenuItem jMenuItem2 = new JMenuItem();
        JMenu jMenu3 = new JMenu();
        ButtonGroup buttonGroup1 = new ButtonGroup();
        JRadioButton filterPort = new JRadioButton();
        JRadioButton filterDestination = new JRadioButton();
        JRadioButton filterContent = new JRadioButton();
        JRadioButton filterCompany = new JRadioButton();
        JRadioButton filterAny = new JRadioButton();
        JLabel jLabel1 = new JLabel();
        jTextField1 = new javax.swing.JTextField();
        JScrollPane jScrollPane1 = new JScrollPane();
        jTable1 = new javax.swing.JTable();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton back = new JButton();
        JButton register = new JButton();
        JRadioButton filterid = new JRadioButton();
        JButton details = new JButton();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Journey management");
        setPreferredSize(new Dimension(900, 340));

        buttonGroup1.add(filterPort);
        filterPort.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 8)); // NOI18N
        filterPort.setText("Port of Origin");
        filterPort.addActionListener(this::filterPortSelected);

        buttonGroup1.add(filterDestination);
        filterDestination.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 8)); // NOI18N
        filterDestination.setText("Destination");
        filterDestination.addActionListener(this::filterDestinationSelected);

        buttonGroup1.add(filterContent);
        filterContent.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 8)); // NOI18N
        filterContent.setText("Content");
        filterContent.addActionListener(this::filterContentSelected);

        buttonGroup1.add(filterCompany);
        filterCompany.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 8)); // NOI18N
        filterCompany.setText("Company");
        filterCompany.addActionListener(this::filterCompanySelected);

        buttonGroup1.add(filterAny);
        filterAny.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 8)); // NOI18N
        filterAny.setText("Any");
        filterAny.addActionListener(this::filterAnySelected);

        jLabel1.setFont(new java.awt.Font("Tahoma", Font.BOLD, 8)); // NOI18N
        jLabel1.setText("Search Filter:");

        jTextField1.setFont(new java.awt.Font("Tahoma", Font.ITALIC, 11)); // NOI18N
        jTextField1.setText("search");
        jTextField1.addActionListener(evt -> jTextField1ActionPerformed());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        		Controller.Requests.tableJourneySetter(mode, "client", filter, jTextField1.getText())
,
            new String[]  {
                "ID", "Port of Origin", "Destination", "Content", "Company", "Container ID", "Status"
            }
        ));
        
        jTable1.setDefaultEditor(Object.class, null);
        jScrollPane1.setViewportView(jTable1);

        back.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::BackActionPerformed);

        register.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        register.setText("Register New");
        register.addActionListener(this::RegisterActionPerformed);

        buttonGroup1.add(filterid);
        filterid.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 8)); // NOI18N
        filterid.setText("ID");
        filterid.addActionListener(this::filterIDSelected);

        details.setText("Journey Details");
        details.addActionListener(this::DetailsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(filterContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterDestination, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterAny, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterPort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(details)
                        .addGap(69, 69, 69)
                        .addComponent(register)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterAny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterDestination)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterContent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterCompany)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterid)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(details))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        new JourneyRegister();
        JourneyRegister.newScreen();
        dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:


        new ClientMainMenu();
        ClientMainMenu.newScreen();
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        // TODO add your handling code here:
    	int row = jTable1.getSelectedRow();
        ArrayList<Jou> jouz = Controller.company.getJourneyDatabase().searchJourney(((Client) Controller.activeUser).getClientID(), "Client");
        
        JourneyDB clientJourneys=new JourneyDB();
        clientJourneys.setJourneys(jouz);
        
        if (mode.equals("filter")) {jouz = clientJourneys.searchJourney(searchword, filter);}
        Jou J = jouz.get(row);						
        ClientJourneyContainer_Details.newScreen(J);
        dispose();
    	
        ClientJourneyContainer_Details.newScreen(J);
        dispose();
    }//GEN-LAST:event_DetailsActionPerformed

    private void filterAnySelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        mode = "filter";
        filter = "None";
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void filterPortSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    	mode = "filter";
        filter = "Port of Origin";
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void filterDestinationSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    	mode = "filter";
        filter = "Destination";
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void filterContentSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    	mode = "filter";
        filter = "Content";
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void filterCompanySelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    	mode = "filter";
        filter = "Company";
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void filterIDSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        mode = "filter";
        filter = "ID";
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    
    /**
     * 
     */
    public static void newScreen() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientJourney().setVisible(true));
        
    }

    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
